# monitoring/fluentd/fluentd.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%L
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

    <match kubernetes.**>
      @type forward
      <server>
        host fluentd-aggregator
        port 24224
      </server>
    </match>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    <filter **>
      @type record_transformer
      enable_ruby true
      <record>
        log_time ${time.strftime('%Y-%m-%dT%H:%M:%S%z')}
        log_namespace ${record['kubernetes']['namespace_name']}
        log_pod ${record['kubernetes']['pod_name']}
        log_container ${record['kubernetes']['container_name']}
      </record>
    </filter>

    <match **>
      @type elasticsearch
      host elasticsearch
      port 9200
      index_name fluentd
      logstash_format true
      flush_interval 10s
    </match>
